revoke delete on table "public"."segments" from "anon";

revoke insert on table "public"."segments" from "anon";

revoke references on table "public"."segments" from "anon";

revoke select on table "public"."segments" from "anon";

revoke trigger on table "public"."segments" from "anon";

revoke truncate on table "public"."segments" from "anon";

revoke update on table "public"."segments" from "anon";

revoke delete on table "public"."segments" from "authenticated";

revoke insert on table "public"."segments" from "authenticated";

revoke references on table "public"."segments" from "authenticated";

revoke select on table "public"."segments" from "authenticated";

revoke trigger on table "public"."segments" from "authenticated";

revoke truncate on table "public"."segments" from "authenticated";

revoke update on table "public"."segments" from "authenticated";

revoke delete on table "public"."segments" from "service_role";

revoke insert on table "public"."segments" from "service_role";

revoke references on table "public"."segments" from "service_role";

revoke select on table "public"."segments" from "service_role";

revoke trigger on table "public"."segments" from "service_role";

revoke truncate on table "public"."segments" from "service_role";

revoke update on table "public"."segments" from "service_role";

alter table "public"."segments" drop constraint "segments_pkey";

drop index if exists "public"."segments_pkey";

drop table "public"."segments";

create table "public"."blandida" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "cook" jsonb not null
);


alter table "public"."blandida" enable row level security;

CREATE UNIQUE INDEX blandida_pkey ON public.blandida USING btree (id);

alter table "public"."blandida" add constraint "blandida_pkey" PRIMARY KEY using index "blandida_pkey";

grant delete on table "public"."blandida" to "anon";

grant insert on table "public"."blandida" to "anon";

grant references on table "public"."blandida" to "anon";

grant select on table "public"."blandida" to "anon";

grant trigger on table "public"."blandida" to "anon";

grant truncate on table "public"."blandida" to "anon";

grant update on table "public"."blandida" to "anon";

grant delete on table "public"."blandida" to "authenticated";

grant insert on table "public"."blandida" to "authenticated";

grant references on table "public"."blandida" to "authenticated";

grant select on table "public"."blandida" to "authenticated";

grant trigger on table "public"."blandida" to "authenticated";

grant truncate on table "public"."blandida" to "authenticated";

grant update on table "public"."blandida" to "authenticated";

grant delete on table "public"."blandida" to "service_role";

grant insert on table "public"."blandida" to "service_role";

grant references on table "public"."blandida" to "service_role";

grant select on table "public"."blandida" to "service_role";

grant trigger on table "public"."blandida" to "service_role";

grant truncate on table "public"."blandida" to "service_role";

grant update on table "public"."blandida" to "service_role";


